name: Build Mikrotik RSC

on:
  push:
    branches: [ main ]
  schedule:
    # каждый день в 00:00 UTC
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1) Клонируем репозиторий и оставляем креды для пуша
      - uses: actions/checkout@v3
        with:
          persist-credentials: true

      # 2) Скачиваем актуальный hosts из оригинального репо
      - name: Fetch original hosts
        run: |
          curl -sSL -o hosts \
            https://raw.githubusercontent.com/pumPCin/AntiZapret/main/hosts

      # 3) Генерируем mikrotik/update-hosts.rsc
      - name: Generate update-hosts.rsc
        run: |
          mkdir -p mikrotik
          # Удаляем старые записи из address-list
          echo "/ip dns static remove [find address-list=\"autohost\"]" \
            > mikrotik/update-hosts.rsc

          declare -A seen
          cnt=0

          # Проходим по всем активным строкам hosts
          while read -r ip rest; do
            for d in $rest; do

              # Пропускаем localhost / broadcasthost
              if [[ "$ip" == "127.0.0.1" && \
                   ( "$d" == "local" || "$d" == "localhost" || "$d" == "localhost.localdomain" ) ]]; then
                continue
              fi
              if [[ "$ip" == "255.255.255.255" && "$d" == "broadcasthost" ]]; then
                continue
              fi

              # Заменяем 0.0.0.0 на TEST-NET-1 blackhole, чтобы RouterOS не ругался
              if [[ "$ip" == "0.0.0.0" ]]; then
                ip_addr="192.0.2.1"
              else
                ip_addr="$ip"
              fi

              # Уникальность по "IP|домен"
              key="$ip_addr|$d"
              if [[ -n "${seen[$key]}" ]]; then
                continue
              fi
              seen[$key]=1

              # Добавляем запись в DNS Static с привязкой в address-list
              echo "/ip dns static add name=$d address=$ip_addr ttl=1d address-list=autohost" \
                >> mikrotik/update-hosts.rsc
              cnt=$((cnt+1))
            done
          done < <(grep -Ev '^(#|$)' hosts)

          # Логируем результат в конце скрипта
          echo "/log info \"[update-hosts] Added $cnt entries\"" \
            >> mikrotik/update-hosts.rsc

          # И сразу выводим в лог Actions
          echo ":: Generated $cnt unique entries"

      # 4) Коммитим и пушим микротик-скрипт обратно в ваш форк
      - name: Commit & Push update-hosts.rsc
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git add mikrotik/update-hosts.rsc
          git diff --quiet --cached || git commit -m "Rebuild Mikrotik RSC: $cnt entries"
          git push origin main
